import './globals.css'
import { Playfair_Display, Source_Serif_4 } from 'next/font/google'

const playfair = Playfair_Display({ subsets: ['latin'] })
const sourceSerif = Source_Serif_4({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-black text-white min-h-screen ${sourceSerif.className}`}>{children}</body>
    </html>
  )
}
